id: P007943
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159533
  title: བོད་ཀྱི་གསོ་རིག་ལོ་རྒྱུས་སྐོར་གྱི་དྲིས་ལན་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་གཟིངས།
  author: ''
  volumes:
    c5b5095fe2274335a75994cda04c9f58:
      image_group_id: I2PD19624
      title: ''
      volume_number: 1
      total_pages: 158
ebook_metadata:
  title: བོད་ཀྱི་གསོ་རིག་ལོ་རྒྱུས་སྐོར་གྱི་དྲིས་ལན་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་གཟིངས།
  author: ''
  sku: P007943
  cover: cover.jpg
  layers:
  - pagination
